# Generated by Django 5.2.7 on 2025-10-11 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_type', models.CharField(choices=[('classic', 'Классическая'), ('premium', 'Премиум'), ('mini', 'Мини')], max_length=20)),
                ('spreads', models.PositiveIntegerField(default=10)),
                ('comment', models.TextField(blank=True)),
                ('delivery_type', models.CharField(choices=[('pickup', 'Самовывоз (0 ₸)'), ('courier', 'Курьер (доставка по городу)'), ('post', 'Почта / EMS / Посылка')], default='pickup', max_length=20)),
                ('delivery_address', models.CharField(blank=True, max_length=512)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('spreads_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные при получении'), ('qr', 'Оплата по QR'), ('online', 'Онлайн-платёж (gateway)')], default='cash', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('failed', 'Неудача')], default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('accepted', 'Принят'), ('printing', 'Заказ печатается'), ('ready', 'Готов к выдаче')], default='accepted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='orders.order')),
            ],
        ),
    ]
