# Generated by Django 5.2.7 on 2025-10-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='individual_spreads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='paper_size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='print_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='product_type',
            field=models.CharField(choices=[('hard', 'Фотокнига — твёрдый переплет'), ('soft', 'Фотокнига — мягкие страницы'), ('print', 'Печать на фотобумаге')], default='hard', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_books',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderfile',
            name='book_index',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderfile',
            name='slot_index',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderfile',
            name='slot_type',
            field=models.CharField(default='spread', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='book_type',
            field=models.CharField(blank=True, choices=[('classic', 'Классическая'), ('premium', 'Премиум'), ('mini', 'Мини')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='spreads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('accepted', 'Принят'), ('printing', 'Печатается'), ('ready', 'Готов')], default='new', max_length=20),
        ),
    ]
