# Generated by Django 5.2.7 on 2025-11-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_individual_spreads_order_paper_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderfile',
            name='book_index',
        ),
        migrations.RemoveField(
            model_name='orderfile',
            name='slot_index',
        ),
        migrations.RemoveField(
            model_name='orderfile',
            name='slot_type',
        ),
        migrations.AlterField(
            model_name='order',
            name='book_type',
            field=models.CharField(choices=[('classic', 'Классическая'), ('premium', 'Премиум'), ('mini', 'Мини')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='individual_spreads',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='paper_size',
            field=models.CharField(choices=[('a4', 'A4'), ('a5', 'A5'), ('square', 'Квадрат')], default='a4', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='print_type',
            field=models.CharField(choices=[('digital', 'Цифровая печать'), ('offset', 'Офсетная печать')], default='digital', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_type',
            field=models.CharField(choices=[('hard', 'Твёрдая обложка'), ('soft', 'Мягкая обложка'), ('print', 'Печать без обложки')], default='hard', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='spreads',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('done', 'Готов')], default='new', max_length=20),
        ),
    ]
