# Generated by Django 5.2.7 on 2025-11-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderfile_book_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfile',
            name='book_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
