# Generated by Django 5.2.7 on 2025-11-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderfile_book_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfile',
            name='slot_type',
            field=models.CharField(choices=[('cover', 'Обложка'), ('pages', 'Страницы')], default='pages', max_length=20),
        ),
    ]
