# Generated by Django 5.2.7 on 2025-11-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderfile_slot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfile',
            name='slot_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
