# Generated by Django 5.2.7 on 2025-11-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderfile_slot_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfile',
            name='book_index',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderfile',
            name='slot_type',
            field=models.CharField(default='spread', max_length=20),
        ),
    ]
