# Generated by Django 5.2.7 on 2025-11-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orderfile_book_index_alter_orderfile_slot_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('accepted', 'Принят'), ('printing', 'Печатается'), ('ready', 'Готов'), ('archived', 'В архиве')], default='new', max_length=20),
        ),
    ]
