# Generated by Django 5.2.7 on 2025-11-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'Принят'), ('printing', 'Печатается'), ('done', 'Готов'), ('archived', 'В архиве')], default='new', max_length=20),
        ),
    ]
